# Generated by Django 5.2.3 on 2025-07-05 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicules', '0003_alter_vehicule_facture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entretien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('kilometrage', models.IntegerField()),
                ('type_entretien', models.TextField()),
                ('facture', models.ImageField(upload_to='factures')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicules.vehicule')),
            ],
        ),
    ]
