# Generated by Django 5.2.3 on 2025-07-05 14:54

import entretiens.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entretiens', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entretien',
            name='facture',
            field=models.FileField(upload_to='factures', validators=[entretiens.models.validateur_extentions]),
        ),
    ]
