# Generated by Django 5.2.5 on 2025-08-30 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entretiens', '0002_alter_entretien_facture'),
        ('vehicules', '0006_alter_vehicules_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entretien',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='entretien',
            name='vehicule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entretiens', to='vehicules.vehicules'),
        ),
    ]
