# Generated by Django 5.2.5 on 2025-08-30 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entretiens', '0003_alter_entretien_options_alter_entretien_vehicule'),
        ('vehicules', '0006_alter_vehicules_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntretienPlanifie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_prevue', models.CharField(blank=True, help_text='Format: mm/aa', max_length=5, null=True)),
                ('kilometrage_prevu', models.IntegerField(blank=True, null=True)),
                ('type_entretien', models.CharField(max_length=200)),
                ('effectue', models.BooleanField(default=False)),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entretiens_planifies', to='vehicules.vehicules')),
            ],
            options={
                'verbose_name': 'Entretien planifié',
                'verbose_name_plural': 'Entretiens planifiés',
                'ordering': ['date_prevue', 'kilometrage_prevu'],
            },
        ),
    ]
