# Generated by Django 5.2.3 on 2025-06-10 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proprietaires', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marque', models.CharField(max_length=50)),
                ('modele', models.CharField(max_length=50)),
                ('annee', models.IntegerField()),
                ('annee_achat', models.DateField()),
                ('kilometrage_achat', models.IntegerField()),
                ('couleur', models.CharField(max_length=50)),
                ('immatriculation', models.CharField(max_length=50)),
                ('chevaux_fiscaux', models.IntegerField()),
                ('chevaux_din', models.IntegerField()),
                ('photo', models.ImageField(upload_to='')),
                ('proprietaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proprietaires.proprietaire')),
            ],
        ),
    ]
