# Generated by Django 5.2.3 on 2025-07-05 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicules', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicule',
            name='facture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
