# Generated by Django 5.2.3 on 2025-07-05 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicules', '0002_vehicule_facture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicule',
            name='facture',
            field=models.ImageField(blank=True, null=True, upload_to='factures'),
        ),
    ]
