# Generated by Django 5.2.5 on 2025-08-29 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entretiens', '0002_alter_entretien_facture'),
        ('proprietaires', '0001_initial'),
        ('vehicules', '0003_alter_vehicule_facture'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vehicule',
            new_name='Vehicules',
        ),
    ]
