# Generated by Django 5.2.5 on 2025-08-29 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicules', '0004_rename_vehicule_vehicules'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicules',
            options={'verbose_name': 'Véhicule', 'verbose_name_plural': 'Véhicules'},
        ),
        migrations.AddField(
            model_name='vehicules',
            name='kilometrage',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
