# Generated by Django 5.2.5 on 2025-08-30 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicules', '0005_alter_vehicules_options_vehicules_kilometrage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicules',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
