# Generated by Django 5.2.5 on 2025-09-02 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicules', '0006_alter_vehicules_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicules',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
    ]
