# Generated by Django 5.2.5 on 2025-09-12 18:01

import django.db.models.deletion
import vehicules.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicules', '0007_alter_vehicules_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_document', models.CharField(choices=[('assurance', 'Assurance'), ('controle_technique', 'Contrôle technique'), ('carte_grise', 'Carte grise'), ('facture_achat', "Facture d'achat"), ('facture_entretien', "Facture d'entretien"), ('autre', 'Autre')], max_length=50)),
                ('nom', models.CharField(help_text='Nom du document', max_length=200)),
                ('fichier', models.FileField(upload_to='documents/', validators=[vehicules.models.validateur_extensions_document])),
                ('date_document', models.DateField(blank=True, help_text='Date du document', null=True)),
                ('date_expiration', models.DateField(blank=True, help_text="Date d'expiration (si applicable)", null=True)),
                ('date_upload', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, help_text='Notes ou commentaires', null=True)),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='vehicules.vehicules')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['type_document', 'nom'],
            },
        ),
    ]
